class LLMClient:
    def generate(self, prompt):
        """
        Generate a response from the language model.

        This is currently a mock implementation.
        A real LLM such as Amazon Bedrock will be connected later.
        """

        return f"""
AI SECURITY ANALYSIS

{prompt}

This response is currently generated by the mock LLM client.
Amazon Bedrock will be connected in the next stage.
"""